'use client';import {useMemo,useState} from 'react';
export function clamp(v:number,min:number,max:number){return Math.min(Math.max(v??0,min),max)}
export function formatINR(n:number){return n.toLocaleString('en-IN',{maximumFractionDigits:0})}
export function Input({label,value,onChange,placeholder,type='text',error}:{label:string;value:any;onChange:(v:any)=>void;placeholder?:string;type?:string;error?:string;}){return(<label className='text-sm block'><span className='label'>{label}</span><input type={type} value={value} onChange={(e)=>onChange(e.target.value)} placeholder={placeholder} className={`input mt-1 ${error?'border-rose-400':''}`} />{error&&<span className='text-rose-400 text-xs'>{error}</span>}</label>)}
export function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[];}){return(<label className='text-sm block'><span className='label'>{label}</span><select value={value} onChange={(e)=>onChange(e.target.value)} className='input mt-1'>{options.map(opt=><option key={opt} value={opt}>{opt}</option>)}</select></label>)}
export function RangeInput({label,min,max,step,value,onChange}:{label:string;min:number;max:number;step:number;value:number;onChange:(v:number)=>void;}){return(<div className='mt-4'><div className='flex items-center justify-between'><span className='text-sm text-neutral-300'>{label}</span><span className='text-xs text-neutral-400'>{min} – {max}</span></div><input type='range' min={min} max={max} step={step} value={value} onChange={(e)=>onChange(clamp(Number(e.target.value),min,max))} className='w-full accent-amber-400'/></div>)}
export function StatCard({label,value}:{label:string;value:string;}){return(<div className='stat'><p className='stat-label'>{label}</p><p className='stat-value'>{value}</p></div>)}
export function FAQ({q,a}:{q:string;a:string;}){const[open,setOpen]=useState(false);return(<div className='rounded-xl border border-white/10 overflow-hidden'><button onClick={()=>setOpen(!open)} className='w-full flex items-center justify-between px-4 py-3 bg-white/5'><span className='font-medium'>{q}</span><span className={`transition ${open?'rotate-90':''}`}>›</span></button>{open&&<div className='px-4 py-3 text-neutral-300 text-sm bg-neutral-900'>{a}</div>}</div>)}
export function useEMI(P:number,annualRate:number,months:number){return useMemo(()=>{const principal=Number(P)||0;const r=(Number(annualRate)||0)/12/100;const n=Number(months)||0;if(principal<=0||r<=0||n<=0)return{emi:0,totalInterest:0,totalPayable:0};const emi=principal*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1);const totalPayable=emi*n;const totalInterest=totalPayable-principal;return{emi,totalInterest,totalPayable};},[P,annualRate,months])}
export function validIndianMobile(m:string){return /^(?:(?:\+?91[-\s]?)?[6-9]\d{9})$/.test(String(m).trim())}
